// Image paths for each product from public/Assets folder
const productImages = {
  "linear-modular-workstation": [
    "/Assets/Linear Modular Workstation/this_is_the_image_i_202606161231 (3).jpeg",
    "/Assets/Linear Modular Workstation/this_is_the_image_i_202606161231 (4).jpeg",
    "/Assets/Linear Modular Workstation/this_is_the_image_i_202606161231 (5).jpeg",
  ],
  "l-type-modular-workstation": [
    "/Assets/L-Type Modular Workstation/this_is_the_image_i_202606161155.jpeg",
    "/Assets/L-Type Modular Workstation/this_is_the_image_i_202606161156.jpeg",
    "/Assets/L-Type Modular Workstation/this_is_the_image_i_202606161232 (2).jpeg",
  ],
  "sharing-workstation-side-modesty": [
    "/Assets/Sharing Workstation — Side Modesty/this_is_the_image_i_202606161150 (1).jpeg",
    "/Assets/Sharing Workstation — Side Modesty/this_is_the_image_i_202606161150.jpeg",
  ],
  "sharing-workstation-c-leg": [
    "/Assets/Sharing Workstation — C Type Leg/this_is_the_image_i_202606161223 (2).jpeg",
    "/Assets/Sharing Workstation — C Type Leg/this_is_the_image_i_202606161224 (1).jpeg",
    "/Assets/Sharing Workstation — C Type Leg/this_is_the_image_i_202606161224.jpeg",
  ],
  "sharing-l-type-workstation": [
    "/Assets/Sharing L-Type Workstation/this_is_the_image_i_202606161246 (1).jpeg",
    "/Assets/Sharing L-Type Workstation/this_is_the_image_i_202606161246.jpeg",
  ],
  "conference-table": [
    "/Assets/Conference Table — C : D Leg/this_is_the_image_i_202606161224 (2).jpeg",
    "/Assets/Conference Table — C : D Leg/this_is_the_image_i_202606161247 (1).jpeg",
    "/Assets/Conference Table — C : D Leg/this_is_the_image_i_202606161247.jpeg",
  ],
  "round-meeting-table": [
    "/Assets/Round Meeting Table/this_is_the_image_i_202606161247 (2).jpeg",
    "/Assets/Round Meeting Table/this_is_the_image_i_202606161247 (3).jpeg",
    "/Assets/Round Meeting Table/this_is_the_image_i_202606161247 (4).jpeg",
  ],
  "120-degree-workstation": [
    "/Assets/120° Workstation/this_is_the_image_i_202606161248 (1).jpeg",
    "/Assets/120° Workstation/this_is_the_image_i_202606161248 (2).jpeg",
    "/Assets/120° Workstation/this_is_the_image_i_202606161248.jpeg",
  ],
  "cabin-table": [
    "/Assets/Cabin Table — D Type Leg/this_is_the_image_i_202606161248 (3).jpeg",
    "/Assets/Cabin Table — D Type Leg/this_is_the_image_i_202606161248 (4).jpeg",
    "/Assets/Cabin Table — D Type Leg/this_is_the_image_i_202606161248 (5).jpeg",
  ],
  "linear-modular-workstation-glass": [
    "/Assets/Linear Modular Workstation — Glass/glass_workstation_2.jpg",
    "/Assets/Linear Modular Workstation — Glass/glass_workstation_3.jpg",
    "/Assets/Linear Modular Workstation — Glass/glass_workstation_1.jpg"
  ],
  "cabin-executive-table": [
    "/Assets/Cabin Executive Table/generate_high_quality_image_of_202606171713.jpeg",
  ],
};

export const products = [
  {
    slug: "l-type-modular-workstation",
    code: "LMW-L",
    name: "L-Type Modular Workstation",
    tagline: "Corner configuration for maximum desk surface. Available in 1200 and 1500 mm widths with perforated side and front modesty panels.",
    img: productImages["l-type-modular-workstation"][0],
    gallery: productImages["l-type-modular-workstation"],
    benefits: [
      "Generous workspace: L-shape corner layout provides ample surface area for dual monitors, documents and peripheral equipment.",
      "Integrated cable management: CRCA powder coated electrical raceway with WireManager and flip-up box keeps all cabling neatly concealed.",
      "Perforated modesty panels: Leg with perforated side modesty and front modesty with perforation for a clean, professional finish.",
    ],
    specs: [
      { label: "Sizes (W × D)", value: "1200 / 1500 × 600 mm" },
      { label: "Structure", value: "CRCA powder coated under structure" },
      { label: "Raceway", value: "CRCA powder coated electrical" },
      { label: "Cable Access", value: "WireManager / Flip-up box" },
      { label: "Modesty", value: "Perforated side & front" },
      { label: "Lead time", value: "3–4 weeks" },
    ],
    features: ["Corner layout", "Cable raceway", "Perforated modesty"],
    applications: ["Manager cabins", "Team leads", "Project rooms"],
  },
  {
    slug: "sharing-workstation-side-modesty",
    code: "SMW-S",
    name: "Sharing Workstation — Side Modesty",
    tagline: "Multi-seat bench system with perforated side modesty. Available in 900, 1050 and 1200 mm widths with built-in electrical raceway.",
    img: productImages["sharing-workstation-side-modesty"][0],
    gallery: productImages["sharing-workstation-side-modesty"],
    benefits: [
      "Cost-effective open-plan solution: Shared understructure between workstations reduces material without compromising on build quality.",
      "Perforated acoustic modesty: Side and front modesty panels with perforation provide visual privacy while maintaining airflow.",
      "Complete wire management: CRCA powder coated electrical raceway with WireManager and flip-up box for clean, organised cabling.",
    ],
    specs: [
      { label: "Sizes (W × D)", value: "1200 / 1050 / 900 × 600 mm" },
      { label: "Structure", value: "CRCA powder coated under structure" },
      { label: "Raceway", value: "CRCA powder coated electrical" },
      { label: "Cable Access", value: "Wire Manager / Flip-up box" },
      { label: "Modesty", value: "Perforated side & front" },
      { label: "Lead time", value: "3–4 weeks" },
    ],
    features: ["Shared understructure", "Perforated modesty", "Wire management"],
    applications: ["Open-plan offices", "BPO & call centres", "Co-working spaces"],
  },
  {
    slug: "120-degree-workstation",
    code: "DEG-120",
    name: "120° Workstation",
    tagline: "Triangular cluster configuration ideal for collaborative open-plan offices. CRCA powder coated structure with integrated cable management and perforated modesty.",
    img: productImages["120-degree-workstation"][0],
    gallery: productImages["120-degree-workstation"],
    benefits: [
      "Space-efficient cluster layout: 120-degree configuration allows three workstations to share a central spine, making efficient use of floor space.",
      "Integrated cable management: CRCA powder coated raceway with WireManager and flip-up box routes all cabling from a central point.",
      "Perforated side modesty: Leg with perforated side modesty provides visual separation between seats while maintaining an open feel.",
    ],
    specs: [
      { label: "Configuration", value: "Three-pod 120° cluster" },
      { label: "Structure", value: "CRCA powder coated under structure" },
      { label: "Raceway", value: "CRCA powder coated raceway" },
      { label: "Cable Access", value: "WireManager / Flip-up box" },
      { label: "Modesty", value: "Perforated side" },
      { label: "Lead time", value: "4 weeks" },
    ],
    features: ["120° cluster", "Shared cable spine", "Perforated modesty"],
    applications: ["Creative studios", "Customer support teams", "Collaborative offices"],
  },
  {
    slug: "linear-modular-workstation",
    code: "LMW-01",
    name: "Linear Modular Workstation",
    tagline: "India's most versatile bench system. Available in 900, 1050 and 1200 mm widths with SQ.50 or SQ.40 pipe frame and integrated electrical raceway.",
    img: productImages["linear-modular-workstation"][0],
    gallery: productImages["linear-modular-workstation"],
    benefits: [
      "Fully modular and scalable: Workstations connect end-to-end to accommodate any team size — from small offices to 200-seat floors.",
      "Heavy-duty CRCA structure: Powder coated cold-rolled carbon steel understructure and electrical raceway built for daily commercial use.",
      "Integrated wire management: Built-in WireManager and flip-up box keeps power and data cables neatly organised at every seat.",
    ],
    specs: [
      { label: "Sizes (W × D)", value: "1200 / 1050 / 900 × 600 mm" },
      { label: "Pipe Size", value: "SQ. 50 or SQ. 40" },
      { label: "Structure", value: "CRCA powder coated under structure" },
      { label: "Raceway", value: "CRCA powder coated electrical" },
      { label: "Cable Access", value: "WireManager / Flip-up box" },
      { label: "Lead time", value: "3–4 weeks" },
    ],
    features: ["Modular bench", "SQ pipe frame", "Cable raceway", "Scalable"],
    applications: ["IT offices", "Banking & finance floors", "BPO & co-working spaces"],
  },
  {
    slug: "sharing-workstation-c-leg",
    code: "SMW-C",
    name: "Sharing Workstation — C Type Leg",
    tagline: "Sleek C-type leg design with SQ.50 or SQ.40 pipe frame. Available in 900, 1050 and 1200 mm widths with perforated side and front modesty.",
    img: productImages["sharing-workstation-c-leg"][0],
    gallery: productImages["sharing-workstation-c-leg"],
    benefits: [
      "Modern C-type leg profile: The C-leg frame gives sharing workstations a contemporary, open look while maintaining structural rigidity.",
      "Perforated side and front modesty: Full panel coverage with perforation for an organised, professional workspace appearance.",
      "Complete cable management: CRCA powder coated electrical raceway with WireManager and flip-up box at every workstation.",
    ],
    specs: [
      { label: "Sizes (W × D)", value: "1200 / 1050 / 900 × 600 mm" },
      { label: "Pipe Size", value: "SQ. 50 or SQ. 40" },
      { label: "Structure", value: "CRCA powder coated under structure" },
      { label: "Raceway", value: "CRCA powder coated electrical" },
      { label: "Cable Access", value: "WireManager / Flip-up box" },
      { label: "Modesty", value: "Perforated side & front" },
    ],
    features: ["C-type leg", "SQ pipe frame", "Perforated modesty", "Cable raceway"],
    applications: ["Corporate offices", "Design studios", "Premium fit-outs"],
  },
  {
    slug: "sharing-l-type-workstation",
    code: "SLW-01",
    name: "Sharing L-Type Workstation",
    tagline: "L-shaped sharing configuration for collaborative team environments. Available in 1200 and 1500 mm widths with perforated side and front modesty.",
    img: productImages["sharing-l-type-workstation"][0],
    gallery: productImages["sharing-l-type-workstation"],
    benefits: [
      "L-shaped team configuration: Combines the space efficiency of a sharing bench with the added surface area of an L-type layout.",
      "Full perforated modesty: Leg with side modesty and front modesty with perforation for a clean, well-defined workspace.",
      "Integrated cable routing: CRCA powder coated raceway with WireManager and flip-up box at every seat.",
    ],
    specs: [
      { label: "Sizes (W × D)", value: "1200 / 1500 × 600 mm" },
      { label: "Structure", value: "CRCA powder coated under structure" },
      { label: "Raceway", value: "CRCA powder coated raceway" },
      { label: "Cable Access", value: "Wire Manager / Flip-up box" },
      { label: "Modesty", value: "Perforated side & front" },
      { label: "Lead time", value: "3–4 weeks" },
    ],
    features: ["L-shape sharing", "Perforated modesty", "Cable management"],
    applications: ["Team clusters", "Engineering & design teams", "Collaborative offices"],
  },
  {
    slug: "conference-table",
    code: "CFT-01",
    name: "Conference Table — C / D Leg",
    tagline: "Boardroom-ready table available from 2100 to 3000 mm. CRCA powder coated structure with centre leg riser cover for concealed cable routing.",
    img: productImages["conference-table"][0],
    gallery: productImages["conference-table"],
    benefits: [
      "Multiple size options: Available in 2100, 2400 and 3000 mm lengths with 900 or 1200 mm width to suit any boardroom.",
      "Concealed cable management: Centre leg houses a riser cover that routes power and data cables cleanly to the floor.",
      "CRCA powder coated structure: Durable cold-rolled carbon steel understructure and electrical raceway with flip-up box access.",
    ],
    specs: [
      { label: "Sizes (L × W)", value: "2100 / 2400 / 3000 × 900 / 1200 mm" },
      { label: "Structure", value: "CRCA powder coated under structure" },
      { label: "Raceway", value: "CRCA powder coated electrical" },
      { label: "Cable Access", value: "Flip-up box" },
      { label: "Leg", value: "C or D profile with centre riser cover" },
      { label: "Lead time", value: "4–5 weeks" },
    ],
    features: ["C or D leg", "Riser cover", "Flip-up box", "Multiple sizes"],
    applications: ["Boardrooms", "Meeting rooms", "Executive briefing rooms"],
  },
  {
    slug: "round-meeting-table",
    code: "RNT-01",
    name: "Round Meeting Table",
    tagline: "Compact round tables in 750, 900 and 1200 mm diameters. CRCA powder coated structure with integrated electrical raceway.",
    img: productImages["round-meeting-table"][0],
    gallery: productImages["round-meeting-table"],
    benefits: [
      "Three diameter options: Available in 750, 900 and 1200 mm to suit small huddle rooms or mid-size meeting spaces.",
      "CRCA powder coated understructure: Durable cold-rolled carbon steel base with powder coat finish for long-term commercial use.",
      "Integrated electrical raceway: Built-in CRCA powder coated raceway for clean power and data management at the table.",
    ],
    specs: [
      { label: "Diameters", value: "750 / 900 / 1200 mm" },
      { label: "Structure", value: "CRCA powder coated under structure" },
      { label: "Raceway", value: "CRCA powder coated electrical" },
      { label: "Lead time", value: "2–3 weeks" },
    ],
    features: ["Multiple diameters", "CRCA structure", "Electrical raceway"],
    applications: ["Huddle rooms", "Small meeting spaces", "Breakout areas"],
  },
  {
    slug: "cabin-table",
    code: "CBT-D",
    name: "Cabin Table — D Type Leg",
    tagline: "Executive cabin table with D-type leg. Available in 1200, 1500 and 1800 mm widths with CRCA powder coated structure and perforated modesty panels.",
    img: productImages["cabin-table"][0],
    gallery: productImages["cabin-table"],
    benefits: [
      "Three width options: Available in 1200, 1500 and 1800 mm widths × 750 mm depth to suit cabin sizes from small to large.",
      "D-type leg profile: Clean, professional leg design with CRCA power coated structure for strength and durability.",
      "Perforated modesty panels: Leg with perforated side modesty and front modesty with perforation for a neat, finished look.",
    ],
    specs: [
      { label: "Sizes (W × D)", value: "1200 / 1500 / 1800 × 750 mm" },
      { label: "Structure", value: "CRCA power coated structure" },
      { label: "Leg", value: "D-type" },
      { label: "Modesty", value: "Perforated side & front" },
      { label: "Lead time", value: "3–4 weeks" },
    ],
    features: ["D-type leg", "Three width options", "Perforated modesty"],
    applications: ["Manager cabins", "Director offices", "Private offices"],
  },
  {
    slug: "linear-modular-workstation-glass",
    code: "LMW-GL",
    name: "Linear Modular Workstation — Glass",
    tagline: "Linear bench with 8mm lacquered glass screen dividers. Available in 900, 1050 and 1200 mm widths with mobile drawer pedestal.",
    img: productImages["linear-modular-workstation-glass"][0],
    gallery: productImages["linear-modular-workstation-glass"],
    benefits: [
      "Glass screen dividers: 32 or 45 mm frame with 8mm lacquered glass provides visual separation while maintaining a bright, open office feel.",
      "Mobile drawer pedestal: Includes a mobile drawer pedestal for personal storage that moves with the user.",
      "CRCA powder coated structure: Durable understructure and electrical raceway with WireManager for clean cable management.",
    ],
    specs: [
      { label: "Sizes (W × D)", value: "1200 / 1050 / 900 × 600 mm" },
      { label: "Structure", value: "CRCA powder coated under structure" },
      { label: "Raceway", value: "CRCA powder coated raceway" },
      { label: "Screen", value: "32 / 45 mm frame, 8 mm lacquered glass" },
      { label: "Storage", value: "Mobile drawer pedestal" },
      { label: "Lead time", value: "3–4 weeks" },
    ],
    features: ["Glass screen", "Mobile pedestal", "Cable raceway", "CRCA structure"],
    applications: ["Corporate offices", "Premium fit-outs", "Executive open-plan areas"],
  },
  {
    slug: "cabin-executive-table",
    code: "CBT-EX",
    name: "Cabin Executive Table — D Type Leg",
    tagline: "Premium executive table with D-type leg architecture. Available in 1200, 1500 and 1800 mm widths with full perforated side and front modesty.",
    img: productImages["cabin-executive-table"][0],
    gallery: productImages["cabin-executive-table"],
    benefits: [
      "Executive proportions: Available in 1200, 1500 and 1800 mm widths × 750 mm depth to furnish any size of director or senior manager cabin.",
      "D-type leg design: Clean, professional leg profile with CRCA powder coated structure for a polished executive appearance.",
      "Full perforated modesty: Side and front modesty panels with perforation provide a tidy, professional finish from all angles.",
    ],
    specs: [
      { label: "Sizes (W × D)", value: "1200 / 1500 / 1800 × 750 mm" },
      { label: "Leg", value: "D-type" },
      { label: "Structure", value: "CRCA powder coated" },
      { label: "Modesty", value: "Perforated side & front" },
      { label: "Lead time", value: "3–4 weeks" },
    ],
    features: ["D-type leg", "Full perforated modesty", "Executive scale", "Three widths"],
    applications: ["Executive cabins", "Director offices", "Senior management suites"],
  },
];

export function getProduct(slug) {
  return products.find((p) => p.slug === slug);
}
